# WebSocket Server Configuration File
# This file can be customized and placed anywhere, then specified via SERVER_CONFIG_PATH environment variable

# Message Queue Configuration
message_queue:
  threshold: 1 # Minimum number of messages to trigger queue processing
  sleep_duration: 0.2 # Sleep duration in seconds when queue is below threshold
  error_sleep_duration: 1.0 # Sleep duration in seconds after an error occurs

# Server Configuration
server:
  host: "0.0.0.0" # Bind to all interfaces for production-like behavior
  port: 8000 # Server port
  workers: 1 # Number of worker processes for production-like settings
  keep_alive_timeout: 5 # Keep-alive timeout in seconds
  concurrency_limit: 100 # Maximum concurrent connections
  max_requests_per_worker: 1000 # Max requests per worker before restart

# Room and Document Configuration
room:
  default_document_content: |
    def main():
        print('Hello, world!')
    if __name__ == '__main__':
        main()

# Example of how to override values with environment variables:
# MESSAGE_QUEUE_THRESHOLD=5 python server.py
# SERVER_HOST=localhost python server.py
# SERVER_PORT=9000 python server.py

